gossip_project3_app/config/routes.rb
Rails.application.routes.draw do
  
  get 'gossips/index'
  get 'gossips/new'
  get 'gossips/edit'
  get 'gossips/show'

  resources :gossips
  

  resources :users
  get 'users/show'
  get 'users/index'
  
  resources :cities
  get 'cities/show'

  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  get '/home/:id', to: 'static#home_id'
  get '/home', to: 'static#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

gossip_project3_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

gossip_project3_app/app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

gossip_project3_app/app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user

	has_many :join_table_tag_gossips
	has_many :tags, through: :join_table_tag_gossips

	validates :title, length: { in: 3..15}
	validates :content, presence: true
	#validates :user_id, presence: false
	#validates :user, presence: false

end

gossip_project3_app/app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord

	belongs_to :gossip
	belongs_to :tag
end

gossip_project3_app/app/models/private_message.rb
class PrivateMessage < ApplicationRecord

	belongs_to :recipient, class_name: "User"
	belongs_to :sender, class_name: "User"
end

gossip_project3_app/app/models/tag.rb
class Tag < ApplicationRecord

	has_many :join_table_tag_gossips
	has_many :gossips, through: :join_table_tag_gossips
end

gossip_project3_app/app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips

	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

gossip_project3_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

gossip_project3_app/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  	@id_city = params[:id]



  end



  def index
  	
  end
end

gossip_project3_app/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
  	@gossips = Gossip.all 
  end

  def create
    Gossip.create(title: "#{params[:gossip][:title]}", content: "#{params[:gossip][:content]}", user_id: 4)
    redirect_to gossips_index_path
  end


  def new
    @gossip = Gossip.new

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(title: "#{params[:gossip][:title]}", content: "#{params[:gossip][:content]}", user_id: 4)
    redirect_to gossips_index_path

  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_index_path
  end

  def show
	@id_lien = params[:id]
  @gossip_one = Gossip.find(params[:id])
  @gossip_del = Gossip.find(params[:id]).id
  @id_user = User.find(Gossip.find(params[:id]).user_id).id
  @coment = Tag.find(JoinTableTagGossip.find(Gossip.find(params[:id]).id).gossip_id).title
  end

end

gossip_project3_app/app/controllers/static_controller.rb
class StaticController < ApplicationController
  
  def team
  end

  def contact
  end

  def home_id
  puts "$" * 60 
  puts params[:id]
  puts "$" * 60

  @user = params[:id]	
  end


  def home
  	
  end

end

gossip_project3_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
 @id_user = params[:id]
 @id_city = City.find(User.find(params[:id]).city_id)

 puts "$$" *60
 puts params
 puts "$$" *60
  end
end

gossip_project3_app/app/helpers/application_helper.rb
module ApplicationHelper
end

gossip_project3_app/app/helpers/cities_helper.rb
module CitiesHelper
end

gossip_project3_app/app/helpers/gossips_helper.rb
module GossipsHelper
end

gossip_project3_app/app/helpers/static_helper.rb
module StaticHelper
end

gossip_project3_app/app/helpers/user_helper.rb
module UserHelper
end

gossip_project3_app/app/helpers/users_helper.rb
module UsersHelper
end

gossip_project3_app/app/views/cities/show.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Voici la ville de l'auteur :</p><br>



<div class="card" style="width: 18rem;">
<h5 class="card-body">Ville: <u><%=City.find(@id_city).name%> </u></h5>

</div>

gossip_project3_app/app/views/gossips/edit.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Tu vas pouvoir editer ce Gossip, à toi de jouer !!</p><br>


<%= form_for @gossip do |f| %>
	<div class="form-group">
	<label>Titre du Gossip</label><br>
  <%= f.text_field :title %><br><br>
	<label>Contenu du Gossip</label><br>
  <%= f.text_area :content, size: "60x3" %><br><br>
  <%= f.submit "Modifier" %>
  </div>
<% end %>

gossip_project3_app/app/views/gossips/index.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<h2>Tu peux cliquer sur ce lien pour créer un nouveau Gossip</h2><br>

<p><a href="<%= new_gossip_path %>">Création Gossip</a></p>
<br><br><hr><br><br>


<h2>Voici les potins :</h2><br><br>

<div class="div_to_hide"> <%= @gossips.each do |gossip|%></div>
<div class="div_main">
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Auteur: <u><%=User.find(gossip.user_id).first_name%> <%=User.find(gossip.user_id).last_name%></u></h5>
    <h6 class="card-subtitle mb-2 text-muted">Titre: <%= gossip.title %></h6>
    <p class="card-text">Si tu es curieux, tu peux cliquer sur le lien ci-dessous pour aller découvrir le contenu de ce gossip</p>
    <a href="<%= gossip_path(gossip.id) %>" class="card-link">Lien du Gossip</a>
  </div>
</div>
</div>
<div class="div_to_hide"><% end %></div>

gossip_project3_app/app/views/gossips/new.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Tu vas pouvoir enregister ton propre Gossip via ce formulaire, à toi de jouer !!</p><br>



  
<%= form_for @gossip, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
	<div class="form-group">
	<label>Titre du Gossip</label><br>
  <%= f.text_field :title %><br><br>
	<label>Contenu du Gossip</label><br>
  <%= f.text_area :content, size: "60x3" %><br><br>
  <%= f.submit "Créer" %>
  </div>
<% end %>

gossip_project3_app/app/views/gossips/show.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Voici ton potin préféré :</p><br>



<div class="card" style="width: 600px;">
  <div class="card-body">
    <h5 class="card1-title">Auteur: <u><%= User.find(Gossip.find(@id_lien).user_id).first_name %> <%= User.find(Gossip.find(@id_lien).user_id).last_name %></u></h5>
    <p>City: <u><%= City.find(User.find(Gossip.find(@id_lien).user_id).city_id).name %></u></p> <hr><br>
    <h6 class="card1-subtitle mb-2 text-muted">Titre: <%= @gossip_one.title %></h6>
    <p class="card1-text">Contenu: <%= @gossip_one.content %></p>
    <a href="<%= edit_gossip_path(@gossip_one.id) %>" class="card1-link">Editer le Gossip</a>
	
	<a href="<%= gossip_path(@gossip_one.id) %>" class="card1-link" data-confirm="Êtes-vous certain ?" data-method="DELETE">Supprimer le Gossip</a><br>
    
    <a href="<%= user_path(@id_user) %>" class="card1-link">Voir l'Auteur</a>

    <a href="<%= gossips_index_path %>" class="card1-link">Retour Index</a>
  </div>
  <div class="card-body">Commentaires:<p><%= @coment %></p></div>
</div>

gossip_project3_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>GossipProjectApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="http://localhost:3000/home">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="http://localhost:3000/gossips/index">Index</a>
      <a class="nav-item nav-link" href="http://localhost:3000/team">Team</a>
      <a class="nav-item nav-link" href="http://localhost:3000/contact">Contact</a>
      <a class="nav-item nav-link disabled" href="#">Disabled</a>
    </div>
  </div>
</nav>
</header>

  <body>
    <div class="div1">
    <%= yield %>
    </div>
  </body>
</html>

gossip_project3_app/app/views/users/show.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Voici ton auteur préféré :</p><br>


<div class="card" style="width: 600px;">
  <div class="card-body">
    <h5 class="card1-title"> <%=User.find(@id_user).last_name%> <%=User.find(@id_user).first_name%></h5><hr>
    <p class="card1-text">Age: <%=User.find(@id_user).age%> ans<br>E-mail: <%=User.find(@id_user).email%><br>Ville: <%=City.find(User.find(@id_user).city_id).name%><br><br><u>Description:</u> <br><%=User.find(@id_user).description%><br></p>
    <a href="<%= city_path(@id_city.id) %>" class="card1-link">Voir la ville</a>
  </div>
</div>